### ISSUE TITLE
H.264 error with wgpu example

### ISSUE THREAD

**Issue by snow2flying** [livekit/rust-sdks#169] opened 2023-08-31 05:09 UTC
got the following error when I run the wgpu_room example:

ERROR libwebrtc] (h264_decoder_impl.cc:312): FFmpeg H.264 decoder not found

and when I check my ffmpeg I got this:

ffmpeg -codecs | grep 264
ffmpeg version 5.1.3-1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_qsv h264_cuvid ) (encoders: libx264 libx264rgb h264_nvenc h264_omx h264_qsv h264_v4l2m2m h264_vaapi )

**Comment by davidzhao** [comment] 2023-08-31 05:11
which version of the SDK did you get this error with?

**Comment by snow2flying** [comment] 2023-08-31 05:35
client-sdk-rust:
commit c7465925c77ea2dda14dad50f4cd3436521d67dc (HEAD -> main, tag: webrtc-a59e857, origin/main, origin/HEAD)
livekit server:
v1.4.5

**Comment by snow2flying** [comment] 2023-09-01 05:15
yes I do have ffmpeg with h264 installed on my laptop.

my os:
>     lsb_release -a
> No LSB modules are available.
> Distributor ID:	Debian
> Description:	Debian GNU/Linux 12 (bookworm)
> Release:	12
> Codename:	bookworm

this is how I installed ffmpeg:
>     apt install ffmpeg

this is how I check ffmpeg with h264:

>      ffmpeg -codecs | grep 264
> ffmpeg version 5.1.3-1 Copyright (c) 2000-2022 the FFmpeg developers
> built with gcc 12 (Debian 12.2.0-14)
> configuration: --prefix=/usr --extra-version=1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-sndio --enable-libjxl --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-libplacebo --enable-librav1e --enable-shared
> libavutil 57. 28.100 / 57. 28.100
> libavcodec 59. 37.100 / 59. 37.100
> libavformat 59. 27.100 / 59. 27.100
> libavdevice 59. 7.100 / 59. 7.100
> libavfilter 8. 44.100 / 8. 44.100
> libswscale 6. 7.100 / 6. 7.100
> libswresample 4. 7.100 / 4. 7.100
> libpostproc 56. 6.100 / 56. 6.100
> DEV.LS h264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_qsv h264_cuvid ) (encoders: libx264 libx264rgb h264_nvenc h264_omx h264_qsv h264_v4l2m2m h264_vaapi )

this is my  client-sdk-rust:
>     git log
> commit c7465925c77ea2dda14dad50f4cd3436521d67dc (HEAD -> main, tag: webrtc-fcdef0d, tag: webrtc-a59e857, origin/main, origin/HEAD)
> Author: Théo Monnom <theo.monnom@outlook.com>
> Date:   Tue Aug 29 10:51:14 2023 -0700
> 
> add e2ee deps to webrtc patches (#167)

this is how I run the example:

> cd  client-sdk-rust/examples/  &&  cargo  run  -p wgpu_room --release

**Comment by snow2flying** [comment] 2023-09-01 05:23
and my rust version:

> stable-x86_64-unknown-linux-gnu (default)
> rustc 1.72.0 (5680fa18f 2023-08-23)

**Comment by snow2flying** [comment] 2023-09-01 05:28
and also tonight I compiled and installed the latest ffmpeg from source code. The error is still the same.
This is my new ffmpeg:

>     ffmpeg -codecs | grep 264
> ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
>   built with gcc 12 (Debian 12.2.0-14)
>   configuration: --enable-nonfree --enable-gpl --enable-openssl --enable-libdav1d --enable-libsvtav1 --enable-librav1e --enable-libx264 --enable-libx265 --enable-libvpx --enable-libxvid --enable-libvidstab --enable-libaom --enable-libzimg --enable-lv2 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libtheora --enable-libfdk-aac --enable-libwebp --enable-libsrt --disable-ffnvcodec --enable-amf --disable-debug --disable-shared --enable-pthreads --enable-static --enable-version3 --extra-cflags='-I/home/damo/install/ffmpeg/ffmpeg-build-script/workspace/include -I/home/damo/install/ffmpeg/ffmpeg-build-script/workspace/include/lilv-0' --extra-ldexeflags= --extra-ldflags=-L/home/damo/install/ffmpeg/ffmpeg-build-script/workspace/lib --extra-libs='-ldl -lpthread -lm -lz' --pkgconfigdir=/home/damo/install/ffmpeg/ffmpeg-build-script/workspace/lib/pkgconfig --pkg-config-flags=--static --prefix=/home/damo/install/ffmpeg/ffmpeg-build-script/workspace --extra-version=
>   libavutil      58.  2.100 / 58.  2.100
>   libavcodec     60.  3.100 / 60.  3.100
>   libavformat    60.  3.100 / 60.  3.100
>   libavdevice    60.  1.100 / 60.  1.100
>   libavfilter     9.  3.100 /  9.  3.100
>   libswscale      7.  1.100 /  7.  1.100
>   libswresample   4. 10.100 /  4. 10.100
>   libpostproc    57.  1.100 / 57.  1.100
>  DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m ) (encoders: libx264 libx264rgb h264_amf h264_v4l2m2m )

**Comment by theomonnom** [comment] 2023-09-01 05:33
Seems like you don't have --enable-libopenh264?

**Comment by snow2flying** [comment] 2023-09-01 12:33
I compiled ffmpeg with libopenh264 enabled, but the error is still the same:
>     ffmpeg -codecs |grep openh264
> ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
>   built with gcc 12 (Debian 12.2.0-14)
>   configuration: --enable-nonfree --enable-gpl --enable-openssl --enable-libdav1d --enable-libsvtav1 --enable-librav1e --enable-libx264 --enable-libx265 --enable-libvpx --enable-libxvid --enable-libvidstab --enable-libaom --enable-libzimg --enable-lv2 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libtheora --enable-libfdk-aac --enable-libwebp --enable-libsrt --disable-ffnvcodec --enable-amf --disable-debug --disable-shared --enable-pthreads --enable-static --enable-version3 --enable-libopenh264 --extra-cflags='-I/home/damo/install/ffmpeg/ffmpeg-build-script/workspace/include -I/home/damo/install/ffmpeg/ffmpeg-build-script/workspace/include/lilv-0' --extra-ldexeflags= --extra-ldflags=-L/home/damo/install/ffmpeg/ffmpeg-build-script/workspace/lib --extra-libs='-ldl -lpthread -lm -lz' --pkgconfigdir=/home/damo/install/ffmpeg/ffmpeg-build-script/workspace/lib/pkgconfig --pkg-config-flags=--static --prefix=/home/damo/install/ffmpeg/ffmpeg-build-script/workspace --extra-version=
>   libavutil      58.  2.100 / 58.  2.100
>   libavcodec     60.  3.100 / 60.  3.100
>   libavformat    60.  3.100 / 60.  3.100
>   libavdevice    60.  1.100 / 60.  1.100
>   libavfilter     9.  3.100 /  9.  3.100
>   libswscale      7.  1.100 /  7.  1.100
>   libswresample   4. 10.100 /  4. 10.100
>   libpostproc    57.  1.100 / 57.  1.100
>  DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m libopenh264 ) (encoders: libx264 libx264rgb libopenh264 h264_amf h264_v4l2m2m )
>

this is the error:
> [2023-09-01T12:28:47Z ERROR libwebrtc] (h264_decoder_impl.cc:312): FFmpeg H.264 decoder not found.
> [2023-09-01T12:28:47Z ERROR libwebrtc] (decoder_database.cc:148): Failed to initialize decoder.
>

**Comment by theomonnom** [comment] 2023-09-03 06:39
mb a regression due to https://github.com/livekit/client-sdk-rust/pull/130 ?

**Comment by snow2flying** [comment] 2023-09-11 16:26
what is your building os platform?
I tried Windows too. I could not get it built successfully.

**Comment by snow2flying** [comment] 2023-09-11 16:30
can you put compiling descriptions in the readme? that will be helpful

**Comment by davidzhao** [comment] 2023-11-13 06:10
we'll update the library so it works out of the box.

**Comment by theomonnom** [comment] 2023-11-13 21:08
Fixed by #241

**Closed by theomonnom** 2023-11-13 21:08 UTC
Labels: bug
